#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
delugevpn () {                # name must match file; make sure it's unique

container_reset                  # do not delete this
# VARIABLES ####################################################################
pgrole="delugevpn"            # name this of the exact file name
image="binhex/arch-delugevpn"      # image nameto pull
port_inside01="8112"            # port for inside container
port_outside01="8112"           # port for outside container / how accessed
port_inside02="58846"            # port for inside container
port_outside02="58846"           # port for outside container / how accessed
port_inside03="58946"            # port for inside container
port_outside03="58946"           # port for outside container / how accessed
port_inside04="8118"            # port for inside container
port_outside04="8118"           # port for outside container / how accessed
traefik_extport="8112"          # how traefik reaches the external port

# PATHS ########################################################################
# 1st - path on your server # 2nd - path of the container

container_path /pg /pg
container_path /pg/unity /pg/unity
container_path /pg/data/$pgrole /config/$pgrole
container_path /etc/localtime /etc/localtime:ro

# PERMISSIONS ##################################################################
# pay attention, to exactly what's required for permissions
container_permissions GUID 1000
container_permissions PGID 1000

# CONTAINER EXTRA ENVS #########################################################
# Not required, but an example is placed below incase; delete # to use
# container_oddball capabilities SYS_PTRACE

# IMAGES EXPORT - 1ST IS DEFAULT ###############################################
# how users select an image; the 1st image is the default. If only 1, it's ok!
cat <<- EOF > "/pg/images/$pgrole.images"
binhex/arch-delugevpn:latest
binhex/arch-delugevpn:latest
EOF

# YML EXPORT ###################################################################
# You should not have to edit anything below!
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

### END OF FILE ################################################################
EOF
}
